"""send token enable flag

Revision ID: 218bd1aad26c
Revises: cdd7fffc7357
Create Date: 2026-03-29 23:48:09.470716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '218bd1aad26c'
down_revision: Union[str, Sequence[str], None] = 'cdd7fffc7357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('is_send_token_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'is_send_token_enabled')
    # ### end Alembic commands ###
