"""remove vendor logic temporally

Revision ID: cdd7fffc7357
Revises: 9c9424d9cfd5
Create Date: 2026-03-28 22:15:53.014101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd7fffc7357'
down_revision: Union[str, Sequence[str], None] = '9c9424d9cfd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'price')
    op.drop_column('apps', 'is_locked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('is_locked', sa.BOOLEAN(), nullable=False))
    op.add_column('apps', sa.Column('price', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
